python_llm_autograder/grading/urls.py
from django.urls import path
from . import views
from .views import SignUpView
from django.conf import settings
from django.conf.urls.static import static
# from grading.dash_apps.finished_apps import AutograderAnalyticsDashboard

urlpatterns = [
    path("", views.home, name="grading-home"), #Empty route pattern matching from project urls.py
    path("history/", views.history, name="grading-history"), #Route pattern matching from project urls.py
    path('delete_submission_batch/<int:pk>/', views.delete_submission_batch, name='delete_submission_batch'),
    path("dashboard/", views.dashboard, name="grading-dashboard"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path('logout/',views.logout_view,name='logout'),
    path("assignment_class/", views.create_course_and_assignment, name="assignment-class"),
    path("question/", views.upload_materials, name="question-upload"),
    path("submission_upload/", views.submission_upload, name="submission-upload"),
    path("model_solution_generator/<int:pk>/", views.model_solution_generator, name="model-solution-generator"),
    path('student-submissions/<int:pk>/', views.student_submissions_list, name='student_submissions_list'),
    path('update_actual_score/<int:pk>/', views.update_actual_score, name='update_actual_score'),
    path('student/<int:pk>/', views.student_submission_detail, name='student_submission_detail'),
    path('question-list/', views.question_list, name='question_list'),
    path('delete_question/<int:pk>/', views.delete_question, name='delete_question'),

    path('ajax/load-assignments/', views.load_assignments, name='ajax_load_assignments'),
    path('ajax/load-questions/', views.load_questions, name='ajax_load_questions'),
    path('ajax/load-course-groups/', views.load_course_groups, name='ajax_load_course_groups')

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

python_llm_autograder/python_llm_autograder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("admin/", admin.site.urls),
    path("", include("grading.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    # path('django_plotly_dash/', include('django_plotly_dash.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

python_llm_autograder/grading/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,User
from django.utils import timezone
# from ckeditor.fields import RichTextField
# Create your models here.

def grading_rubric_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    assignment = instance.assignment.assignment_code
    question = instance.qn_code
    lecturer = instance.lecturer.username
    print()
    return f"{lecturer}/{assignment}/{question}/grading_rubric/{filename}"

def question_file_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    assignment = instance.assignment.assignment_code
    question = instance.qn_code
    lecturer = instance.lecturer.username
    return f"{lecturer}/{assignment}/{question}/question_file/{filename}"

def model_solution_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    assignment = instance.question.assignment.assignment_code
    question = instance.question.qn_code
    lecturer = instance.lecturer.username
    return f"{lecturer}/{assignment}/{question}/model_solution/{filename}"

def ast_python_solution_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    assignment = instance.question.assignment.assignment_code
    question = instance.question.qn_code
    lecturer = instance.lecturer.username
    return f"{lecturer}/{assignment}/{question}/ast_python_solution/{filename}"

def test_cases_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    assignment = instance.assignment.assignment_code
    question = instance.qn_code
    lecturer = instance.lecturer.username
    return f"{lecturer}/{assignment}/{question}/test_cases/{filename}"

def submission_batch_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    assignment = instance.question.assignment.assignment_code
    question = instance.question.qn_code
    lecturer = instance.lecturer.username
    course_group = instance.course_group.class_code
    return f"{lecturer}/{assignment}/{question}/submission_batch/{course_group}/{filename}"
    #return f"{lecturer}/{assignment}/{question}/submission_batch/{filename}"

class Lecturer(AbstractUser):
    pass
    # add additional fields in here

    def __str__(self):
        return self.username

class CourseGroup(models.Model):
    class_code = models.CharField(primary_key=True,max_length=20)
    lecturer = models.ForeignKey(Lecturer, on_delete=models.CASCADE, related_name='course_groups')

    def __str__(self):
        return f"{self.class_code}"

class Assignment(models.Model):
    assignment_code = models.CharField(primary_key=True, max_length=20)
    course_group = models.ManyToManyField(CourseGroup, related_name='assignments')
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        course_codes = ", ".join([cg.class_code for cg in self.course_group.all()])
        return f"{self.assignment_code} (Course Groups: {course_codes})"

class Question(models.Model):
    #not setting qn_code as primary key in case you have multiple 'Q2' code or same assignment code
    qn_code = models.CharField(max_length=10)
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE, related_name='questions')
    #description = models.TextField(null=True)
    lecturer = models.ForeignKey(Lecturer, on_delete=models.CASCADE)    
    grading_rubric = models.FileField(upload_to=grading_rubric_directory_path)
    question_file = models.FileField(upload_to=question_file_directory_path,default= "")
    test_cases_file = models.FileField(upload_to=test_cases_directory_path,default="")
    qn_total_score = models.FloatField(default=0,null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = [['qn_code', 'assignment']]
    def __str__(self):
        return f"{self.qn_code},{self.assignment.assignment_code}"

class ModelSolution(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='model_solutions')
    lecturer = models.ForeignKey(Lecturer, on_delete=models.CASCADE)    
    model_solution = models.FileField(upload_to=model_solution_directory_path)
    model_solution_all_solutions = models.TextField(null=True, blank=True)
    ast_python_code = models.FileField(upload_to=ast_python_solution_directory_path, null=True, blank=True)  # Change to FileField
    

    def __str__(self):
        return f"Model Solution for {self.question.qn_code}"

class SubmissionBatch(models.Model):
    submission_id = models.AutoField(primary_key=True)
    # course_group = models.CharField( default = "", max_length=20)# for storing course group name when saving form to guide file path directory
    # question = models.OneToOneField(Question, on_delete=models.CASCADE, related_name='submission_batch')
    # lecturer = models.ForeignKey(Lecturer, on_delete=models.SET_NULL, null=True, blank=True)# for storing lecturer name when saving form to guide file path directory
    # # form fields to populate upload path
    # course_group = models.CharField(null=True, blank=True,default="",max_length=20)
    # assignment = models.CharField(null=True, blank=True,default="",max_length=20)
    question = models.OneToOneField(
        Question,
        on_delete=models.CASCADE,
    )
    lecturer = models.ForeignKey(
        Lecturer,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    course_group = models.ForeignKey(
        CourseGroup,
        null=True,
        blank=True,
        on_delete=models.SET_NULL
    )
    assignment = models.ForeignKey(
        Assignment,
        null=True,
        blank=True,
        on_delete=models.SET_NULL
    )
    
    student_submissions_zip = models.FileField(upload_to=submission_batch_directory_path)
    uploaded_at = models.DateTimeField(default=timezone.now)
    total_submissions = models.IntegerField(default=0) #TODO: if celery workers wanna update this
    processed_submissions = models.IntegerField(default=0) #TODO: if celery workers wanna update this

    def __str__(self):
        return f"Submission Batch for {self.question.qn_code} with id {self.submission_id}"


class StudentSubmission(models.Model):
    student_id = models.AutoField(primary_key=True) # proof of concept so each student has no id yet #TODO: make into primary key in the future
    submission_batch = models.ForeignKey(SubmissionBatch, on_delete=models.CASCADE, related_name='student_submissions')
    submission_file = models.TextField(max_length=10000)
    needs_manual_review = models.BooleanField(default=False)
    actual_score = models.FloatField(null=True, blank=True)  # Score after lecturer's manual adjustment

    
    # Results from checkers
    test_cases_passed = models.IntegerField(default=0)
    total_test_cases = models.IntegerField(default=0)
    test_cases_feedback = models.JSONField(null=True, blank=True)
    overall_score = models.FloatField(null=True, blank=True,default=0)
    ################################################################
    best_practices_score = models.FloatField(null=True, blank=True)
    best_practices_feedback = models.JSONField(null=True, blank=True)
    ###################################################################
    question_specific_score = models.FloatField(null=True, blank=True)
    question_specific_total_score = models.FloatField(default=0,null=True, blank=True)
    question_specific_feedback = models.JSONField(null=True, blank=True)
    final_suggested_score = models.FloatField(null=True, blank=True)

    # Storing detailed feedback as JSON
    checker_feedback = models.JSONField(null=True, blank=True)

    def __str__(self):
        return f"{self.student_id} - Submission Batch ID: {self.submission_batch.submission_id}"

python_llm_autograder/grading/templates/grading/assignment_class.html
{% extends "grading/base.html" %} {%block content %}
{% load crispy_forms_tags %}
<h1>Form Testing</h1>
<form method="post">
  {% csrf_token %}
  <h2>Assign Assignment to Course Group</h2>

  {{ course_group_form.non_field_errors }}
  <div class="form-group">
      {{ course_group_form.course_group.label_tag }}
      {{ course_group_form.course_group }}
      {% for error in course_group_form.course_group.errors %}
          <div class="error">{{ error }}</div>
      {% endfor %}
  </div>

  <div class="form-group">
      {{ course_group_form.new_class_code.label_tag }}
      {{ course_group_form.new_class_code }}
      {% for error in course_group_form.new_class_code.errors %}
          <div class="error">{{ error }}</div>
      {% endfor %}
  </div>

  {{ assignment_form|crispy }}
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

<div class="row mt-5">
    <div class="col-md-2">
        <table class="table table-dark">
            <thead>
                <tr>
                    <th scope="col">Assignments</th>
                </tr>
            </thead>
            <tbody id="assignment_list">
                <tr>
                    <td>---------</td>
            </tbody>
        </table>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script>
    $(document).ready(function(){
    // When course group changes
    $('#id_course_group').change(function(){
        var courseGroupId = $(this).val();
        console.log(courseGroupId)
        $.ajax({
            url: "{% url 'ajax_load_assignments' %}",
            data: {
                'course_group': courseGroupId
            },
            success: function(data){
                $("#assignment_list").html('');
                $.each(data.assignments, function(key, value){
                    console.log(key, value)
                    $("#assignment_list").append('<tr><td>' + value.assignment_code + '</td></tr>');
                });
            }
        });
    });
});
</script>

{%endblock content%}

python_llm_autograder/grading/templates/grading/base.html
<!-- Repeated sections between html pages, will be included on every page -->
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <!-- <script src= "{% static 'grading/plotly.min.js' %}"></script> -->
    {% comment %} <link rel="stylesheet" href="{% static 'grading/main.css' %}" /> {% endcomment %}
     <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/lux/bootstrap.min.css" />
    {% if title %}
    <title>Grading - {{title}}</title>
    {% else %}
    <title>Grading</title>
    {% endif %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'grading-home' %}">Equinox</a>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          {% comment %} <a class="navbar-brand nav-link" href="{% url 'grading-home' %}">Equinox</a> {% endcomment %}
          <a class="nav-item nav-link {% if not user.is_authenticated %}disabled{% endif %}" href="{% url 'grading-history' %}">History</a>
          <a class="nav-item nav-link {% if not user.is_authenticated %}disabled{% endif %}" href="{% url 'grading-dashboard' %}">Dashboard</a>
          <a class="nav-item nav-link {% if not user.is_authenticated %}disabled{% endif %}" href="{% url 'assignment-class' %}">class,assignment creation</a>
          <a class="nav-item nav-link {% if not user.is_authenticated %}disabled{% endif %}" href="{% url 'question-upload' %}">question</a>       
          <a class="nav-item nav-link {% if not user.is_authenticated %}disabled{% endif %}" href="{% url 'submission-upload' %}">submission</a>       
        </div>
      </div>
    </nav>

    <div class="container">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      {% block content %} {% endblock content %}
    </div>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

python_llm_autograder/grading/templates/grading/dashboard.html
{% extends "grading/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5">
    <h1>Dashboard Page</h1>
    <form method="GET" action="{% url 'grading-dashboard'%}">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-3">
                {{ form.course_group|as_crispy_field }}
            </div>
            <div class="col-md-3">
                {{ form.assignment|as_crispy_field }}
            </div>
            <div class="col-md-3">
                {{ form.question|as_crispy_field }}
            </div>
            <div class="col-md-3" style="margin-top:30px;">
                <button type="submit" class="btn btn-primary">Generate</button>
            </div>
        </div>
        
    </form>
    <hr>

    {% if charts %}
        <!-- Include Plotly.js -->
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
        <div class="fw-bold">
            <h3>Summary Statistics</h3>
            <table class="table table-bordered table-dark">
                <thead>
                    <th>Mean Score</th>
                    <th>Median Score</th>
                    <th>Standard Deviation</th>
                    <th>Overall Score</th>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ filter_params.mean_score|floatformat:2 }}</td>
                        <td>{{ filter_params.median_score|floatformat:2 }}</td>
                        <td>{{ filter_params.std_dev_score|floatformat:2 }}</td>
                        <td>{{ filter_params.overall_score|floatformat:2 }}</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <!-- Divs to hold the charts -->
        <div class="row">
            <div class="col-md-6">
                <h3>Total Marks Distribution</h3>
                <div id="marks-distribution-chart"></div>
            </div>
            <div class="col-md-6">
                <h3>Error Topic Distribution</h3>
                <div id="error-topic-distribution-chart"></div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-md-6">
                <h3>Test Cases Passed Distribution</h3>
                <div id="test-cases-distribution-chart"></div>
            </div>
            <div class="col-md-6">
                <h3>Criteria Met Distribution</h3>
                <div id="criteria-met-distribution-chart"></div>
            </div>
        </div>

        <!-- Scripts to render the charts -->
        <script type="text/javascript">
            var marksDistribution = JSON.parse('{{ charts.marks_distribution|safe }}');
            Plotly.newPlot('marks-distribution-chart', marksDistribution.data, marksDistribution.layout);

            var errorTopicDistribution = JSON.parse('{{ charts.error_topic_distribution|safe }}');
            Plotly.newPlot('error-topic-distribution-chart', errorTopicDistribution.data, errorTopicDistribution.layout);

            var testCasesDistribution = JSON.parse('{{ charts.test_cases_distribution|safe }}');
            Plotly.newPlot('test-cases-distribution-chart', testCasesDistribution.data, testCasesDistribution.layout);

            var criteriaMetDistribution = JSON.parse('{{ charts.criteria_met_distribution|safe }}');
            Plotly.newPlot('criteria-met-distribution-chart', criteriaMetDistribution.data, criteriaMetDistribution.layout);
        </script>
    {% else %}
        <div class="alert alert-info" role="alert">
            <h3 class="alert-heading text-center">Please select a Course Group, Assignment, and Question<br> to generate the dashboard.</h2>
        </div>
    {% endif %}
</div>
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script>
$(document).ready(function(){
    // When course group changes
    $('#id_course_group').change(function(){
        var courseGroupId = $(this).val();
        console.log(courseGroupId)
        $.ajax({
            url: "{% url 'ajax_load_assignments' %}",
            data: {
                'course_group': courseGroupId
            },
            success: function(data){
                console.log("Assignment Filter fires")
                $("#id_assignment").html('<option value="">---------</option>');
                $("#id_question").html('<option value="">---------</option>');
                $.each(data.assignments, function(key, value){
                    $("#id_assignment").append('<option value="' + value.assignment_code + '">' + value.assignment_code + '</option>');
                });
            }
        });
    });

    // When assignment changes
    $('#id_assignment').change(function(){
        var assignmentId = $(this).val();
        console.log(assignmentId)
        $.ajax({
            url: "{% url 'ajax_load_questions' %}",
            data: {
                'assignment': assignmentId
            },
            success: function(data){
                console.log("Question Filter fires")
                $("#id_question").html('<option value="">---------</option>');
                $.each(data.questions, function(key, value){
                    console.log(key, value)
                    $("#id_question").append('<option value="' + value.id + '">' + value.qn_code + '</option>');
                });
            }
        });
    });

    $('#id_question').change(function(){
        var questionId = $(this).val();
        console.log(questionId)
        $.ajax({
            url: "{% url 'ajax_load_course_groups' %}",
            data: {
                'question': questionId
            },
            success: function(data){
                console.log("Course Group Filter fires")
                //$("#id_question").html('<option value="">---------</option>');
                $.each(data.course_groups, function(key, value){
                    console.log(key, value)
                    //$("#id_question").append('<option value="' + value.id + '">' + value.qn_code + '</option>');
                });
            }
        });
    });
});
</script>
{% endblock content %}

python_llm_autograder/grading/templates/grading/history.html
{% extends "grading/base.html" %}
{% block content %}
{% load tz %}
<style>
    .sticky-header th {
        position: sticky;
        top: 0;
        background-color: #343a40;
        color: white;
        z-index: 2; /* Ensure it stays above table body */
        box-shadow: 0 2px 2px -1px rgba(0, 0, 0, 0.4);
    }
</style>

<div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-2">
        <h1>Batch History</h1>
        <a href="{% url 'question_list' %}">
            <h1>Question History</h1>
        </a>
    </div>
    <div class="table-responsive" style="max-height: 500px; overflow-y: auto;">
        <table class="table table-bordered table-striped">
            <thead class="thead-dark sticky-header">
                <tr>
                    <th>ID</th>
                    <th>Course Group</th>
                    <th>Assignment</th>
                    <th>Question</th>
                    <th>Uploaded At</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for batch in submission_batches %}
                <tr>
                    <td>
                      <a href="{% url 'student_submissions_list' batch.pk %}" target="_blank">
                        {{ batch.submission_id }}</td>
                      </a>
                    </td>
                    <td>{{ batch.course_group.class_code }}</td>
                    <td>{{ batch.assignment.assignment_code }}</td>
                    <td>{{ batch.question.qn_code }}</td>
                    <td>{{ batch.uploaded_at|timezone:"Asia/Singapore" }}</td>
                    <td>
                        <form method="post" action="{% url 'delete_submission_batch' batch.pk %}" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-danger">Delete</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

python_llm_autograder/grading/templates/grading/home.html
{% extends "grading/base.html" %} 
{% block content %}

    {% if user.is_authenticated %}
    <div class="container bg-light bg-gradient p-3">
        <h3> Hi {{ user.username }}! </h3>
        <p>
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-dark">Logout</button> | 
                <a href="{% url 'question-upload' %}" class="btn btn-outline-dark">Upload Documents</a>
            </form>
        </p>
    </div>
        {% comment %} {% for post in posts%}
            <h1>{{post.title}}</h1>
            <p>By {{post.author}} on {{post.date}}</p>
            <p>{{post.content}}</p>
        {% endfor%}  {% endcomment %}
    {% else %}
        <div class="container rounded bg-dark p-3 mt-4">
            <h2 class="text-light text-center mb-4">You are not logged in</h2>
            <div class="d-flex justify-content-center">
                <a href="{% url 'login' %}" class="btn btn-primary mx-2">Log In</a> |
                <a href="{% url 'signup' %}" class="btn btn-primary mx-2">Sign Up</a>
            </div>
        </div>
        {% comment %} <p>You are not logged in</p>
        <a href="{% url 'login' %}">Log In</a> |
        <a href="{% url 'signup' %}">Sign Up</a> {% endcomment %}
    {% endif %}
{% endblock content %}

python_llm_autograder/grading/templates/grading/model_solution_generator.html
{% extends "grading/base.html" %}
{%block content %}
{% load crispy_forms_tags %}
<h1>Model Solution Validation</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- <div class="form-group">
            {{ form.course_group.label_tag }}
            {{ form.course_group }}
            {% for error in form.course_group.errors %}
                <div class="error">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.assignment.label_tag }}
            {{ form.assignment }}
            {% for error in form.assignment.errors %}
                <div class="error">{{ error }}</div>
            {% endfor %}

        </div>
        <div class="form-group">
            {{ form.question.label_tag }}
            {{ form.question }}
            {% for error in form.question.errors %}
                <div class="error">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.student_submissions_zip.label_tag }}
            {{ form.student_submissions_zip }}
            {% for error in form.student_submissions_zip.errors %}
                <div class="error">{{ error }}</div>
            {% endfor %}
        </div> -->
        <!-- {{form.media}} -->
        {{form|crispy}}
        <button type="submit" class="btn btn-primary">Upload</button>
    </form>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.5/codemirror.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.5/theme/monokai.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.5/codemirror.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.5/mode/python/python.min.js"></script>

<script>
    var editor = CodeMirror.fromTextArea(document.querySelector('.code-editor'), {
        mode: 'python',
        theme: 'monokai',
        lineNumbers: true,
        indentUnit: 4,
        autoCloseBrackets: true
    });
</script>
<style>
    .CodeMirror {
        height: 500px;
        font-size: 14px;
    }
</style>
{%endblock content%}

python_llm_autograder/grading/templates/grading/question_upload.html
{% extends "grading/base.html" %}
{%block content %}
{% load crispy_forms_tags %}
<h1>Form Testing Question</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h2>Question Details</h2>
        <div id="question_list" style="color: green;"></div>
        {{ question_form|crispy }}

        {{course_group_form|crispy}}
    
        <h2>Model Solution</h2>
        {{ model_solution_form|crispy}}
    
        <button type="submit" class="btn btn-outline-dark">Submit</button>
    </form>

<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script>
$(document).ready(function(){

    // When assignment changes
    $('#id_assignment').change(function(){
        var assignmentId = $(this).val();
        console.log(assignmentId)
        $.ajax({
            url: "{% url 'ajax_load_questions' %}",
            data: {
                'assignment': assignmentId
            },
            success: function(data){
                $("#question_list").html(`Questions for ${assignmentId}: `);
                $.each(data.questions, function(key, value){
                    console.log(key, value)
                    $("#question_list").append(value.qn_code +", ",);
                });
            }
        });
    });
});
</script>

{%endblock content%}

python_llm_autograder/grading/templates/grading/submission_upload.html
{% extends "grading/base.html" %}
{%block content %}
{% load crispy_forms_tags %}
<h1>Student Submission Upload</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- <div class="form-group">
            {{ form.course_group.label_tag }}
            {{ form.course_group }}
            {% for error in form.course_group.errors %}
                <div class="error">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.assignment.label_tag }}
            {{ form.assignment }}
            {% for error in form.assignment.errors %}
                <div class="error">{{ error }}</div>
            {% endfor %}

        </div>
        <div class="form-group">
            {{ form.question.label_tag }}
            {{ form.question }}
            {% for error in form.question.errors %}
                <div class="error">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.student_submissions_zip.label_tag }}
            {{ form.student_submissions_zip }}
            {% for error in form.student_submissions_zip.errors %}
                <div class="error">{{ error }}</div>
            {% endfor %}
        </div> -->
        {{form|crispy}}
        <button type="submit" class="btn btn-primary">Upload</button>
    </form>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script>
    $(document).ready(function(){
    // When course group changes
    $('#id_course_group').change(function(){
        var courseGroupId = $(this).val();
        console.log(courseGroupId)
        $.ajax({
            url: "{% url 'ajax_load_assignments' %}",
            data: {
                'course_group': courseGroupId
            },
            success: function(data){
                $("#id_assignment").html('<option value="">---------</option>');
                $("#id_question").html('<option value="">---------</option>');
                $.each(data.assignments, function(key, value){
                    $("#id_assignment").append('<option value="' + value.assignment_code + '">' + value.assignment_code + '</option>');
                });
                console.log($("#id_assignment").html())
            }
        });
    });

    // When assignment changes
    $('#id_assignment').change(function(){
        var assignmentId = $(this).val();
        console.log(assignmentId)
        $.ajax({
            url: "{% url 'ajax_load_questions' %}",
            data: {
                'assignment': assignmentId
            },
            success: function(data){
                $("#id_question").html('<option value="">---------</option>');
                $.each(data.questions, function(key, value){
                    $("#id_question").append('<option value="' + value.id + '">' + value.qn_code + '</option>');
                });
                console.log($("#id_question").html())
            }
        });
    });
    });
    </script>
{%endblock content%}